services:
  lugs-soc-tools:
    image: ghcr.io/lawrence-lugs/lugs-soc/lugs-soc-tools:latest
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      cache_from:
        - ghcr.io/lawrence-lugs/lugs-soc/lugs-soc-tools:buildcache
    volumes:
      - ..:/workspace
      - conda_pkgs:/root/miniforge3/pkgs
    ports:
      - "8888:8888"
    environment:
      - PDK_ROOT=/foss/pdks
    working_dir: /workspace 
    stdin_open: true
    tty: true
    command: ["--skip", "bash"]

volumes:
  conda_pkgs:
