.PHONY: test-base harden

test-base:
@echo "Running TPU base tests..."
@echo "TODO: Add TPU simulation tests here"

harden:
@echo "Running LibreLane for tpu-build macro..."
@echo "TODO: Run librelane config.yaml"
