// Auto-generated by LibreLane
module lugs_soc_chip(
`ifdef USE_POWER_PINS
  inout IO_CORNER_NORTH_WEST_INST.iovdd_RING,
  inout IO_CORNER_NORTH_WEST_INST.vdd_RING,
  inout IO_CORNER_NORTH_WEST_INST.vss_RING,
`endif
  inout clk_PAD,
  inout nrst_PAD,
  inout uart_tx_PAD,
  inout uart_rx_PAD,
  inout qspi_sck_PAD,
  inout qspi_cs_PAD,
  inout qspi_io0_PAD,
  inout qspi_io1_PAD,
  inout qspi_io2_PAD,
  inout qspi_io3_PAD,
  inout jtag_tck_PAD,
  inout jtag_tms_PAD,
  inout jtag_tdi_PAD,
  inout jtag_tdo_PAD,
  inout gpio0_PAD,
  inout gpio1_PAD,
  inout gpio2_PAD,
  inout gpio3_PAD
);
endmodule
