// Auto-generated by LibreLane
module sram_1rw_32_1024_wrapper(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input cs,
  input we,
  input[9:0] addr,
  input[31:0] wdata,
  input[3:0] wmask,
  output[31:0] rdata
);
endmodule
